services:
    BowlOfSoup\CouchbaseAccessLayer\Factory\ClusterFactory:
        class: BowlOfSoup\CouchbaseAccessLayer\Factory\ClusterFactory
        arguments:
        - %couchbase_access_layer.host%
        - %couchbase_access_layer.user%
        - %couchbase_access_layer.password%

    BowlOfSoup\CouchbaseAccessLayer\Repository\BucketRepository:
        class: BowlOfSoup\CouchbaseAccessLayer\Repository\BucketRepository
        arguments:
        - %couchbase_access_layer.bucket_default%
        - '@BowlOfSoup\CouchbaseAccessLayer\Factory\ClusterFactory'